# Generated by Django 3.0.6 on 2020-06-02 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column_Set',
            fields=[
                ('column_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('column_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Key_Link',
            fields=[
                ('key_ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('key_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Niche',
            fields=[
                ('niche_ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tag', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_Extended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domanin_auth', models.CharField(max_length=500)),
                ('traffic', models.IntegerField()),
                ('spam_score', models.IntegerField()),
                ('existing_cost', models.IntegerField()),
                ('new_cost', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('niche', models.CharField(max_length=500)),
                ('key_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Key_Link')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('domanin_rank', models.IntegerField()),
                ('key_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Key_Link')),
            ],
        ),
    ]
