# Generated by Django 3.0.6 on 2020-06-04 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key_Link_List',
            fields=[
                ('key_link', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='key_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Key_Link_List'),
        ),
        migrations.AlterField(
            model_name='profile_extended',
            name='key_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Key_Link_List'),
        ),
        migrations.DeleteModel(
            name='Key_Link',
        ),
    ]
