# Generated by Django 3.0.6 on 2020-06-05 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20200605_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link_Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compare_key_link', models.CharField(max_length=500)),
                ('no_of_data_matched', models.IntegerField(default=0)),
                ('compare_key_link_no_of_data', models.IntegerField(default=0)),
                ('key_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Key_Link_List')),
            ],
        ),
    ]
