# Generated by Django 3.0.7 on 2020-06-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_auto_20200607_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
