# Generated by Django 3.0.6 on 2020-06-10 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_auto_20200609_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryName',
            fields=[
                ('directory_name', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DirectoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_link', models.CharField(default='', max_length=500)),
                ('directory_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.DirectoryName')),
            ],
        ),
    ]
