# Generated by Django 3.0.7 on 2020-06-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_directoryitem_directoryname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_extended',
            name='traffic',
            field=models.FloatField(),
        ),
    ]
