# Generated by Django 3.0.7 on 2020-06-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_auto_20200613_1555'),
        ('panel', '0007_auto_20200613_1559'),
    ]

    operations = [
    ]
