# Generated by Django 3.0.7 on 2020-06-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_merge_20200613_2025'),
        ('panel', '0008_auto_20200615_1748'),
    ]

    operations = [
    ]
